mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  notEmpty: true
spring:
  ## 数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_db?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=true
    username: root
    password: root
mybatis:
  configLocation: classpath:mybatis/configuration.xml
  mapperLocations: classpath:mybatis/mapper/*-mapper.xml